spring:
  application:
    name: provider
  #设置采样比例为1.0。默认是0.1
  sleuth:
    sampler:
      probability: 1.0

  #Zipkin服务器的地址
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

