server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dantefung/spring-cloud-samples     # \u914D\u7F6Egit\u4ED3\u5E93\u7684\u5730\u5740
          search-paths: config-repo                             # git\u4ED3\u5E93\u5730\u5740\u4E0B\u7684\u76F8\u5BF9\u5730\u5740\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A\uFF0C\u7528,\u5206\u5272\u3002
          # username\u548Cpassword\u662F\u7528\u6237\u540D\u548C\u5BC6\u7801\uFF0C\u516C\u5F00\u4ED3\u5E93\u7684\u8BDD\u53EF\u4EE5\u4E0D\u5199
          username:                                             # git\u4ED3\u5E93\u7684\u8D26\u53F7
          password:                                             # git\u4ED3\u5E93\u7684\u5BC6\u7801
