## 不配置的话 eureka的Instances currently registered with Eureka 的 application 为UNKNOWN
spring:
  application:
    name: spring-cloud-eureka-client

## 不配置的话默认为8080
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/