server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-client
  ## 消息队列配置
  rabbitmq:
    host: 192.168.126.129
    port: 5672
    username: admin
    password: 123456
  ## 开启消息跟踪
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # 注册中心eurka地址